// // Generated by https://quicktype.io

// export interface Countries {
//     status: number;
//     userCountryCode: string;
//     countries: Country[];
//     timezones: Timezone[];
//     userSelectValue: UserSelectValue;
// }

// export interface Country {
//     value: string;
//     label: string;
//     nicename: string;
// }

// export interface Timezone {
//     country_code: string;
//     timezone: string;
// }

// export interface UserSelectValue {
//     value: string;
//     label: string;
//     nicename: string;
//     timezone: string;
// }

export interface Country {
    status: number;
    userCountryCode: string;
    countries: UserSelectValue[];
    timezones: Timezone[];
    userSelectValue: UserSelectValue;
}

export interface UserSelectValue {
    value: string;
    label: string;
    nicename: string;
    timezone?: string;
}

export interface Timezone {
    country_code: string;
    value: string;
    label: string;
}
